spring:
  mail:
      host: smtp.gmail.com
      port: 587
      username: coderstrustemailservice
      password: coderstrustemailservice1234
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true