spring:
  mail:
      host: smtp.gmail.com
      port: 587
      username: coderstrustmailservice@gmail.com
      password: coderstrustmailservice1234
      properties.mail.smtp:
            auth: true
            starttls.enable: true